[package]
name = "my_rust_project"
version = "0.1.0"
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "my_rust_project"
path = "src/main.rs"

[[bin]]
name = "main2"
path = "src/bin/main2.rs"
